(function(){
  const css=document.createElement("style");
  css.textContent=".ta-voice-fab{position:fixed;right:22px;bottom:22px;z-index:9999;border:1px solid rgba(77,163,255,.35);background:#0d131c;color:#fff;border-radius:999px;padding:12px 16px;font-weight:850;box-shadow:0 12px 35px rgba(0,0,0,.4)}.ta-voice-panel{position:fixed;right:22px;bottom:78px;width:360px;max-width:calc(100vw - 30px);z-index:9998;background:#0d1118;border:1px solid #303949;border-radius:16px;padding:16px;color:#fff;box-shadow:0 20px 70px rgba(0,0,0,.6)}.ta-voice-q{background:#090d13;border:1px solid #242b38;border-radius:10px;padding:12px;line-height:1.5;font-size:13px}.ta-voice-row{display:flex;gap:8px;margin-top:10px}.ta-voice-row button{flex:1;padding:10px;border-radius:9px;border:1px solid #303949;background:#151a23;color:#fff;font-weight:800}.ta-voice-row .primary{background:#ff3158;border-color:#ff3158}.ta-voice-status{font-size:10px;color:#8f9aaa;margin-top:9px;text-align:center}.ta-voice-answer{margin-top:10px;color:#cbd3df;font-size:12px;line-height:1.5}";
  document.head.appendChild(css);
  let panel,recorder,stream,chunks=[],turns=[];
  const api=()=>String(localStorage.getItem("botApiUrl")||"https://trading-assistant-production.up.railway.app").replace(/\/$/,"");
  const model=()=>String(localStorage.getItem("activeModel")||"NQ").toUpperCase()==="CRYPTO"?"CRYPTO":"NQ";
  const access=()=>String(localStorage.getItem("edgeflowAccessKey")||"");
  const headers=()=>{const h={"Content-Type":"application/json"};const k=access();if(k)h["X-EDGEFLOW-ACCESS"]=k;return h};
  const esc=v=>String(v??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[c]));
  function speak(t){if(!("speechSynthesis" in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang="fr-CA";u.rate=.96;window.speechSynthesis.speak(u)}
  function render(){if(!panel)return;panel.innerHTML='<b>COACH BUSINESS — '+model()+'</b><div id="taVQ" class="ta-voice-q" style="margin-top:10px">JARVIS est prêt. Appuie sur PARLER et parle-lui naturellement.</div><div class="ta-voice-row"><button class="primary" id="taStart">QUESTION</button><button id="taTalk">◉ PARLER</button></div><div class="ta-voice-row"><button id="taDaily">📊 REVUE DU JOUR</button></div><div id="taVA" class="ta-voice-answer"></div><div id="taVS" class="ta-voice-status">Une question à la fois. Objectif : trouver un levier mesurable.</div>';panel.querySelector("#taStart").onclick=start;panel.querySelector("#taTalk").onclick=toggle;panel.querySelector("#taDaily").onclick=daily}
  async function start(){if(!api()){setStatus("Backend IA non configuré.");return}setStatus("Recherche de la question la plus utile…");try{const r=await fetch(api()+"/api/coach/question",{method:"POST",headers:headers(),body:JSON.stringify({model:model()})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Erreur backend");panel.querySelector("#taVQ").textContent=d.question;setStatus("Question active — réponds avec PARLER.");speak(d.question)}catch(e){setStatus(e.message)}}
  async function daily(){if(!api()){setStatus("Backend IA non configuré.");return}setStatus("Analyse des dernières données…");try{const r=await fetch(api()+"/api/optimization/daily?model="+encodeURIComponent(model()),{headers:headers()});const d=await r.json();if(!r.ok)throw new Error(d.error||"Erreur backend");panel.querySelector("#taVA").textContent=d.text||"Aucune conclusion.";setStatus("Revue terminée. Le coach reste centré sur une seule amélioration à tester.");}catch(e){setStatus(e.message)}}
  function setStatus(t){const x=panel?.querySelector("#taVS");if(x)x.textContent=t}
  function mime(){const a=["audio/mp4","audio/webm;codecs=opus","audio/webm","audio/ogg;codecs=opus"];return a.find(x=>window.MediaRecorder?.isTypeSupported(x))||""}
  async function toggle(){if(recorder?.state==="recording"){recorder.stop();return}if(!api()){setStatus("Backend IA non configuré.");return}if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){setStatus("Micro non disponible dans ce navigateur.");return}try{stream=await navigator.mediaDevices.getUserMedia({audio:true});const m=mime();recorder=m?new MediaRecorder(stream,{mimeType:m}):new MediaRecorder(stream);chunks=[];recorder.ondataavailable=e=>e.data?.size&&chunks.push(e.data);recorder.onstop=()=>{stream?.getTracks().forEach(t=>t.stop());send(new Blob(chunks,{type:recorder.mimeType||m||"audio/webm"}))};recorder.start();setStatus("Je t'écoute… appuie de nouveau pour arrêter.");panel.querySelector("#taTalk").textContent="■ ARRÊTER"}catch(e){setStatus("Micro refusé : "+e.message)}}
  async function send(blob){panel.querySelector("#taTalk").textContent="🎙️ PARLER";setStatus("Transcription et analyse…");const b=await blob.arrayBuffer();let s="",u=new Uint8Array(b);for(let i=0;i<u.length;i+=32768)s+=String.fromCharCode(...u.subarray(i,i+32768));try{const r=await fetch(api()+"/api/voice/turn",{method:"POST",headers:headers(),body:JSON.stringify({model:model(),audioBase64:btoa(s),mimeType:blob.type,previousTurns:turns})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Erreur backend");turns.push({role:"user",content:d.transcript},{role:"assistant",content:d.reply});turns=turns.slice(-12);panel.querySelector("#taVA").innerHTML="<b>Toi :</b> "+esc(d.transcript)+"<br><br><b>Coach :</b> "+esc(d.reply);panel.querySelector("#taVQ").textContent=d.reply;setStatus("Question suivante prête.");if(d.audioBase64){const a=new Audio("data:audio/mpeg;base64,"+d.audioBase64);a.play().catch(()=>speak(d.reply))}else speak(d.reply)}catch(e){setStatus(e.message)}}
  function init(){const b=document.createElement("button");b.className="ta-voice-fab";b.textContent="◉ JARVIS";document.body.appendChild(b);panel=document.createElement("div");panel.className="ta-voice-panel";panel.style.display="none";document.body.appendChild(panel);b.onclick=()=>{panel.style.display=panel.style.display==="none"?"block":"none";if(panel.style.display==="block")render()};}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
})();