
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const MODE_KEY="edgeflow.mode";
const VIEW_KEY="edgeflow.view";
let mode=(new URLSearchParams(location.search).get("mode")||localStorage.getItem(MODE_KEY)||"").toUpperCase();
if(!["NQ","CRYPTO"].includes(mode)) mode="";
let view=new URLSearchParams(location.search).get("view")||localStorage.getItem(VIEW_KEY)||"dashboard";
const state={mode,view,journal:JSON.parse(localStorage.getItem("journal")||"[]")};

const icon={home:"⌂",trades:"▤",perf:"◔",ai:"✦",journal:"▣",analytics:"◫",backtests:"◌",connections:"⌁",settings:"⚙"};
function money(v){const n=Number(v);return Number.isFinite(n)?(n>=0?"+":"-")+"$"+Math.abs(n).toLocaleString("en-US",{maximumFractionDigits:2}):"—"}
function modeName(){return state.mode==="CRYPTO"?"Crypto":"Futures"}
function accent(){return state.mode==="CRYPTO"?"blue":"red"}
function setRoute(v=state.view){const q="?mode="+encodeURIComponent(state.mode)+"&view="+encodeURIComponent(v);history.pushState({},'',q);localStorage.setItem(MODE_KEY,state.mode);localStorage.setItem(VIEW_KEY,v)}
function landing(){
 document.body.innerHTML='<div class="landing"><div class="landing-grid"></div>'+
 '<div class="env futures"><div class="mountains">'+mountain("#ff163f","#26030b")+'</div><div class="env-content"><div><h2>FUTURES</h2><p>MNQ · MES · MGC · RITHMIC · TRADOVATE</p><button class="env-btn" onclick="enterMode(\'NQ\')">ENTER FUTURES <span>→</span></button></div></div></div>'+
 '<div class="env crypto"><div class="mountains">'+mountain("#1598ff","#03162b")+'</div><div class="env-content"><div><h2>CRYPTO</h2><p>BTC · ETH · SOL · BNB · XRP · KCEX</p><button class="env-btn" onclick="enterMode(\'CRYPTO\')">ENTER CRYPTO <span>→</span></button></div></div></div>'+
 '<div class="landing-divider"></div><div class="landing-center"><div class="logo-mark">'+logo("#1598ff")+'</div><div class="logo">EDGE<span>FLOW</span></div><div class="tagline">TRADING INTELLIGENCE</div><div class="choose">CHOOSE YOUR ENVIRONMENT</div></div><div class="landing-footer">DISCIPLINE × DATA × EXECUTION</div></div>';
}
function mountain(a,b){return '<svg viewBox="0 0 900 400" preserveAspectRatio="none"><defs><linearGradient id="mg'+a.slice(1)+'" x1="0" y1="0" x2="0" y2="1"><stop stop-color="'+a+'" stop-opacity=".5"/><stop offset="1" stop-color="'+b+'" stop-opacity=".1"/></linearGradient></defs><path d="M0 400V315L100 255 160 305 255 155 330 275 445 80 560 260 640 185 735 305 825 220 900 300V400Z" fill="url(#mg'+a.slice(1)+' )"/><path d="M0 400V335L120 275 210 340 290 215 390 330 475 145 560 320 650 245 760 335 850 280 900 320V400Z" fill="#02070c" opacity=".78"/><path d="M0 350L130 310 230 345 330 285 440 350 540 275 640 335 760 295 900 345" fill="none" stroke="'+a+'" stroke-opacity=".35" stroke-width="2"/></svg>'}
function logo(c){return '<svg viewBox="0 0 80 80"><path d="M18 12h43L49 25H29l-5 10h25L39 48H18l-7 20h15l6-12h19L40 68H12L27 12Z" fill="'+c+'"/><path d="M27 12 11 68h15l9-31 22-25H27Z" fill="#dff4ff" opacity=".85"/></svg>'}
window.enterMode=m=>{state.mode=m;state.view="dashboard";localStorage.setItem(MODE_KEY,m);localStorage.setItem(VIEW_KEY,"dashboard");location.href="?mode="+m+"&view=dashboard"}
function shell(){
 const isC=state.mode==="CRYPTO", a=isC?"--blue":"--red", a2=isC?"--blue2":"--red2", ag=isC?"--blueglow":"--redglow";
 document.body.style.setProperty("--accent","var("+a+")");document.body.style.setProperty("--accent2","var("+a2+")");document.body.style.setProperty("--accent-glow","var("+ag+")");
 document.body.className=isC?"crypto-mode":"futures-mode";
 document.body.innerHTML='<div class="shell"><aside class="sidebar">'+
 '<div class="brand"><div class="brand-icon">'+logo(isC?"#1598ff":"#ff2048")+'</div><div><div class="brand-name">EDGE<span>FLOW</span></div><div class="brand-sub">TRADING INTELLIGENCE</div></div></div>'+
 '<div class="market-toggle"><button class="'+(!isC?"active futures":"")+'" onclick="enterMode(\'NQ\')">FUTURES</button><button class="'+(isC?"active crypto":"")+'" onclick="enterMode(\'CRYPTO\')">CRYPTO</button></div>'+
 '<div class="nav-label">WORKSPACE</div><div class="nav">'+
 nav("dashboard","Overview","Market command center")+nav("trades","Trades","Execution history")+nav("performance","Performance","Metrics & expectancy")+nav("ai","AI Assistant","Edgeflow intelligence")+nav("journal","Journal","Trading journal")+nav("analytics","Analytics","Deep statistics")+nav("backtests","Backtests","Models & samples")+
 '<div class="nav-label">SYSTEM</div>'+nav("connections","Connections","Broker integrations")+nav("settings","Settings","Environment controls")+
 '</div><div class="sidebar-bottom"><div class="connection-chip"><div><span>EDGEFLOW CORE</span><span class="dot"></span></div><p>'+ (isC?"KCEX · CRYPTO ENGINE":"TRADOVATE · RITHMIC · FUTURES ENGINE")+'</p></div></div></aside>'+
 '<main class="main"><header class="topbar"><div class="crumb">EDGEFLOW CORE <span>•</span> <strong>'+modeName().toUpperCase()+'</strong></div><div class="top-actions"><div class="live"><span class="dot"></span> LIVE</div><div class="session">LDN <b>'+clock()+'</b></div><div class="session">NY <b>'+((new Date().getHours()>=8&&new Date().getHours()<17)?"OPEN":"CLOSED")+'</b></div><div class="avatar">N</div></div></header><section class="workspace" id="workspace"></section></main></div>';
}
function nav(v,t,s){return '<button class="'+(state.view===v?"active":"")+'" onclick="go(\''+v+'\')"><span class="nav-icon">'+icon[v]+'</span><span><strong>'+t+'</strong><small>'+s+'</small></span></button>'}
function clock(){return new Date().toLocaleTimeString("en-US",{hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false})}
function go(v){state.view=v;localStorage.setItem(VIEW_KEY,v);history.pushState({},'',"?mode="+state.mode+"&view="+v);shell();render()}
function kpi(label,value,sub,cls=""){return '<div class="card"><div class="kpi-label">'+label+'</div><div class="kpi-value '+cls+'">'+value+'</div><div class="kpi-sub">'+sub+'</div></div>'}
function pageHead(ey,title,sub,actions=""){return '<div class="page-head"><div><div class="eyebrow">'+ey+'</div><h1>'+title+'</h1><p>'+sub+'</p></div><div class="period">'+actions+'</div></div>'}
function dashboard(){
 const data=state.journal.filter(t=>t.model===state.mode),wins=data.filter(t=>String(t.result).toUpperCase().includes("WIN")).length,loss=data.filter(t=>String(t.result).toUpperCase().includes("LOSS")).length,pnls=data.map(t=>Number(String(t.pnl||"").replace(/[^0-9.-]/g,""))).filter(Number.isFinite),pnl=pnls.reduce((a,b)=>a+b,0),wr=wins+loss?wins/(wins+loss)*100:0;
 return pageHead("MARKET INTELLIGENCE",modeName()+" Dashboard","Account performance, execution context and live market state.",'<select><option>September 2026</option><option>August 2026</option></select><button class="btn primary">LIVE</button>')+
 '<div class="grid-kpi">'+kpi("Account Balance","$49,300.00","Current account balance")+kpi("Today P&L",money(pnl),"Journal-derived",pnl>=0?"positive":"negative")+kpi("Total P&L",money(pnl),"Selected environment",pnl>=0?"positive":"negative")+kpi("Win Rate",wr.toFixed(1)+"%",wins+" wins / "+loss+" losses","accent")+kpi("Win / Loss",wins+" / "+loss,"Recorded trades")+kpi("Profit Factor","—","Calculated from journal")+'</div>'+
 '<div class="market-grid">'+market("MNQ","24,856.25","48 trades · 62%")+market("MES","6,021.75","32 trades · 59%")+market("MGC","3,872.40","18 trades · 67%")+ '<div class="card"><div class="kpi-label">SESSION CONTEXT</div><div class="kpi-value" style="font-size:15px">LONDON / NY / ASIA</div><div class="kpi-sub">Live session state · '+clock()+'</div></div></div>'+
 '<div class="dashboard-grid"><div class="section"><div class="section-head"><div><div class="section-title">RECENT TRADES</div><div class="section-sub">Latest executions in '+modeName()+'</div></div><button class="btn ghost" onclick="go(\'trades\')">VIEW ALL</button></div>'+tradeRows(data.slice(-6).reverse())+'</div><div><div class="section"><div class="section-title">ACCOUNT RULES</div><div class="section-sub">Risk control</div><div class="rule-list" style="margin-top:10px">'+rule("Daily Risk","$1,200")+rule("Consistency","62%")+rule("Max Drawdown","2.1%")+rule("Trades Today",String(data.length))+'</div></div><div class="section model-card"><div class="eyebrow">ACTIVE MODEL</div><div class="model-name">'+(isCryptoModel()?"Crypto Rejection Block":"Rejection Block · Fibonacci")+'</div><div class="tags"><span class="tag">R.B.</span><span class="tag">0.62</span><span class="tag">0.705</span><span class="tag">LIMIT</span></div><div style="margin-top:12px"><button class="btn primary" onclick="go(\'ai\')">OPEN AI</button></div></div></div></div>'+
 '<div class="card" style="margin-top:7px"><div class="kpi-label">MODEL DISCIPLINE</div><div style="display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-top:10px">'+kpi("Retracement","0.5 / 0.62 / 0.705 / 0.79","Allowed Fib levels")+kpi("Entry","LIMIT ORDER","No impulse chase")+kpi("Trigger","REJECTION BLOCK","Primary entry model")+kpi("Structure","HTF → LTF","Context before execution")+'</div></div>';
}
function isCryptoModel(){return state.mode==="CRYPTO"}
function market(s,p,m){return '<div class="card market-card"><div class="market-top"><span class="symbol">'+s+'</span><span class="live-tag">LIVE</span></div><div class="market-price">'+p+'</div><div class="market-meta">'+m+'</div></div>'}
function rule(a,b){return '<div class="rule"><span>'+a+'</span><b>'+b+'</b></div>'}
function tradeRows(data){if(!data.length)return '<div class="empty">No trades recorded yet. Add trades from Journal.</div>';return '<div class="trade-list"><div class="trade-row header"><span>TIME / SYMBOL</span><span>SIDE</span><span>ENTRY</span><span>EXIT</span><span>QTY</span><span>P&L</span><span>R</span></div>'+data.map(t=>'<div class="trade-row"><div><strong>'+esc(t.instrument||"—")+'</strong><div style="color:#52697c;font-size:6px;margin-top:3px">'+esc(t.dateISO||t.date||"")+'</div></div><span class="pill '+(String(t.direction||"").toLowerCase().includes("short")?"short":"long")+'">'+esc(t.direction||"—")+'</span><span>'+esc(t.entry||"—")+'</span><span>'+esc(t.exit||"—")+'</span><span>'+esc(t.quantity||t.qty||"1")+'</span><strong class="'+(Number(t.pnl)>0?"positive":Number(t.pnl)<0?"negative":"")+'">'+money(t.pnl)+'</strong><span>'+esc(t.R||"—")+'</span></div>').join("")+'</div>'}
function trades(){
 const data=state.journal.filter(t=>t.model===state.mode);return pageHead("EXECUTION", "Trades", "Full execution history for this environment.",'<button class="btn primary" onclick="go(\'journal\')">+ NEW JOURNAL ENTRY</button>')+
 '<div class="filters"><input id="tradeSearch" placeholder="Search instrument, setup..." oninput="filterTrades()"><select id="tradeResult" onchange="filterTrades()"><option value="">All results</option><option>WIN</option><option>LOSS</option></select><select><option>All instruments</option></select><button class="btn ghost">EXPORT</button></div><div class="section" id="tradeTable">'+tradeRows(data.slice().reverse())+'</div>';
}
window.filterTrades=()=>{const q=String($("#tradeSearch")?.value||"").toLowerCase(),r=String($("#tradeResult")?.value||"");const data=state.journal.filter(t=>t.model===state.mode&&(!q||JSON.stringify(t).toLowerCase().includes(q))&&(!r||String(t.result).toUpperCase()===r));$("#tradeTable").innerHTML=tradeRows(data.slice().reverse())}
function performance(){const data=state.journal.filter(t=>t.model===state.mode),wins=data.filter(t=>String(t.result).toUpperCase().includes("WIN")).length,loss=data.filter(t=>String(t.result).toUpperCase().includes("LOSS")).length,pnls=data.map(t=>Number(String(t.pnl||"").replace(/[^0-9.-]/g,""))).filter(Number.isFinite);let cum=0;const pts=pnls.map(x=>cum+=x);return pageHead("PERFORMANCE","Performance","Expectancy, P&L curve and setup statistics.",'<button class="btn ghost">30 DAYS</button>')+'<div class="analytics-grid">'+kpi("Total Trades",data.length,"Recorded")+kpi("Win Rate",(wins+loss?wins/(wins+loss)*100:0).toFixed(1)+"%",wins+" / "+loss,"accent")+kpi("Profit Factor","—","Gross profit / gross loss")+kpi("Avg RR","—","From journal R values")+kpi("Net P&L",money(pnls.reduce((a,b)=>a+b,0)),"Selected environment",pnls.reduce((a,b)=>a+b,0)>=0?"positive":"negative")+'</div><div class="content-grid" style="margin-top:8px"><div class="section chart"><div class="section-title">CUMULATIVE P&L</div>'+pnlChart(pts)+'</div><div class="section"><div class="section-title">SETUP BREAKDOWN</div><div class="rule-list" style="margin-top:10px">'+rule("R.B. + FVG","—")+rule("Sweep + OB","—")+rule("10H Open","—")+rule("Trend","—")+'</div></div></div>'}
function pnlChart(pts){if(!pts.length)return '<div class="empty" style="margin-top:15px">No P&L data available.</div>';const min=Math.min(0,...pts),max=Math.max(0,...pts),span=Math.max(1,max-min),d=pts.map((p,i)=>{const x=20+i/Math.max(1,pts.length-1)*95,y=92-(p-min)/span*75;return(i?'L':'M')+x+' '+y}).join(' ');return '<svg viewBox="0 0 120 100" preserveAspectRatio="none"><path d="'+d+'" fill="none" stroke="var(--accent)" stroke-width="1.5"/></svg>'}
function ai(){return pageHead("INTELLIGENCE","AI Assistant","Edgeflow intelligence for analysis, journaling and execution review.",'<span class="status connected">ENGINE READY</span>')+'<div class="ai-layout"><div class="section"><div class="section-title">EDGEFLOW AI</div><div class="section-sub">Your trading intelligence workspace</div><div class="prompt-list" style="margin-top:14px">'+["Analyze my last 5 trades","Check my market context","Find potential retracement setups","Summarize today's journal","Review my discipline","Ask Edgeflow anything..."].map(x=>'<button class="prompt">'+x+' <span style="float:right;color:var(--accent)">→</span></button>').join("")+'</div></div><div class="section"><div class="eyebrow">ACTIVE MODEL</div><div class="model-name">'+(isCryptoModel()?"CRYPTO":"FUTURES")+' · REJECTION BLOCK</div><div class="tags"><span class="tag">RETRACEMENT ONLY</span><span class="tag">LIMIT</span><span class="tag">FIB 0.5</span><span class="tag">0.62</span><span class="tag">0.705</span><span class="tag">0.79</span></div><div class="section-sub" style="margin-top:18px">AI responses should evaluate context, impulse, retracement depth, zone quality, timing and execution—not simply whether the trade won.</div></div></div>'}
function journal(){return pageHead("RECORDS","Journal","Structured trade review and daily execution record.",'<button class="btn primary" onclick="addDemoJournal()">+ ADD ENTRY</button>')+'<div class="journal-layout"><div class="section"><div class="section-title">SEPTEMBER 2026</div><div class="calendar" style="margin-top:13px">'+Array.from({length:30},(_,i)=>'<div class="day '+((i+1)===8?"active":"")+'">'+(i+1)+'</div>').join("")+'</div></div><div class="section"><div class="section-head"><div><div class="section-title">TODAY'S ENTRIES</div><div class="section-sub">Keep the reasoning attached to the execution.</div></div></div>'+tradeRows(state.journal.filter(t=>t.model===state.mode).slice(-5).reverse())+'</div></div>'}
window.addDemoJournal=()=>{state.journal.unshift({id:Date.now(),model:state.mode,dateISO:new Date().toISOString().slice(0,10),instrument:state.mode==="CRYPTO"?"BTC":"MNQ",direction:"Long",entry:"—",exit:"—",quantity:1,pnl:0,R:"—",result:"OPEN",grade:"B+",setup:"R.B. + FVG"});localStorage.setItem("journal",JSON.stringify(state.journal));go("journal")}
function analytics(){return pageHead("ANALYTICS","Analytics","Deep breakdown of execution behavior and model performance.",'<button class="btn ghost">ALL TIME</button>')+'<div class="content-grid"><div class="section">'+kpi("Retracement Model","ACTIVE","Fibonacci + R.B.","accent")+rule("Allowed levels","0.5 · 0.62 · 0.705 · 0.79")+rule("Execution","LIMIT ONLY")+rule("Trigger","REJECTION BLOCK")+rule("Context","HTF → LTF")+'</div><div class="section">'+kpi("Setup Quality","A- / B+ / C+","Grade framework")+rule("A","Solid setup")+rule("B","Good with imperfection")+rule("C","Limit / avoid")+'</div></div>'}
function backtests(){return pageHead("RESEARCH","Backtests","Historical model experiments and sample statistics.",'<button class="btn primary">+ NEW BACKTEST</button>')+'<div class="section"><div class="empty">Backtest workspace ready for your model datasets.</div></div>'}
function connections(){const c=state.mode==="CRYPTO"?["KCEX","Crypto Order Watch","Screen/API integration"]:["Tradovate","Rithmic","Futures order monitoring"];return pageHead("SYSTEM","Connections","Broker connectivity and order visibility for this environment.",'<span class="status connected">CORE ONLINE</span>')+'<div class="connection-grid">'+c.map((x,i)=>'<div class="section connection-card"><div class="kpi-label">'+(i===0?state.mode:"FUTURES")+'</div><h3>'+x+'</h3><span class="status '+(i===0?"connected":"off")+'">'+(i===0?"CONNECTED":"READY")+'</span><p class="section-sub" style="margin-top:15px">'+(x==="KCEX"?"Observe orders from the crypto environment.":"Broker integration endpoint ready for connection.")+'</p><button class="btn ghost" style="margin-top:18px">CONFIGURE</button></div>').join("")+'</div>'}
function settings(){return pageHead("SYSTEM","Settings","Environment preferences and interface controls.",'<button class="btn primary">SAVE</button>')+'<div class="settings-grid"><div class="section">'+setting("Live market state",true)+setting("Order notifications",true)+setting("AI voice",true)+setting("Compact terminal mode",true)+'</div><div class="section">'+setting("Dark mode",true)+setting("Auto refresh",true)+setting("Session indicators",true)+setting("Sound alerts",false)+'</div></div>'}
function setting(n,on){return '<div class="setting"><span>'+n+'</span><span class="switch '+(on?"on":"")+'"></span></div>'}
function render(){const w=$("#workspace");if(!w)return;const pages={dashboard,trades,performance,ai,journal,analytics,backtests,connections,settings};w.innerHTML=(pages[state.view]||dashboard)();document.title="EDGEFLOW — "+modeName()+" · "+state.view.toUpperCase()}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function boot(){if(!state.mode){landing();return}shell();render();setInterval(()=>{$(".session b")?.replaceChildren(document.createTextNode(clock()))},1000)}
window.addEventListener("popstate",()=>{const q=new URLSearchParams(location.search);state.mode=(q.get("mode")||"").toUpperCase();state.view=q.get("view")||"dashboard";if(!["NQ","CRYPTO"].includes(state.mode)){state.mode="";landing()}else{shell();render()}})
boot();
